SET foreign_key_checks = 0;

drop table if exists vote.player;

CREATE TABLE `player` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(45) NOT NULL,
  `last_name` varchar(45) NOT NULL,
  `position_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `positionFK_idx` (`position_id`),
  CONSTRAINT `positionFK` FOREIGN KEY (`position_id`) REFERENCES `position` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE vote.player AUTO_INCREMENT = 1;



INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName0', 'lastName0', 13) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName0'AND last_name like 'lastName0') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName1', 'lastName1', 16) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName1'AND last_name like 'lastName1') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName2', 'lastName2', 2) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName2'AND last_name like 'lastName2') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName3', 'lastName3', 1) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName3'AND last_name like 'lastName3') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName4', 'lastName4', 19) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName4'AND last_name like 'lastName4') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName5', 'lastName5', 13) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName5'AND last_name like 'lastName5') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName6', 'lastName6', 7) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName6'AND last_name like 'lastName6') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName7', 'lastName7', 16) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName7'AND last_name like 'lastName7') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName8', 'lastName8', 14) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName8'AND last_name like 'lastName8') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName9', 'lastName9', 3) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName9'AND last_name like 'lastName9') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName10', 'lastName10', 15) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName10'AND last_name like 'lastName10') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName11', 'lastName11', 12) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName11'AND last_name like 'lastName11') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName12', 'lastName12', 1) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName12'AND last_name like 'lastName12') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName13', 'lastName13', 11) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName13'AND last_name like 'lastName13') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName14', 'lastName14', 1) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName14'AND last_name like 'lastName14') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName15', 'lastName15', 19) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName15'AND last_name like 'lastName15') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName16', 'lastName16', 16) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName16'AND last_name like 'lastName16') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName17', 'lastName17', 3) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName17'AND last_name like 'lastName17') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName18', 'lastName18', 10) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName18'AND last_name like 'lastName18') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName19', 'lastName19', 17) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName19'AND last_name like 'lastName19') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName20', 'lastName20', 16) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName20'AND last_name like 'lastName20') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName21', 'lastName21', 8) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName21'AND last_name like 'lastName21') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName22', 'lastName22', 11) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName22'AND last_name like 'lastName22') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName23', 'lastName23', 16) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName23'AND last_name like 'lastName23') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName24', 'lastName24', 5) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName24'AND last_name like 'lastName24') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName25', 'lastName25', 14) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName25'AND last_name like 'lastName25') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName26', 'lastName26', 5) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName26'AND last_name like 'lastName26') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName27', 'lastName27', 12) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName27'AND last_name like 'lastName27') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName28', 'lastName28', 11) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName28'AND last_name like 'lastName28') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName29', 'lastName29', 8) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName29'AND last_name like 'lastName29') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName30', 'lastName30', 15) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName30'AND last_name like 'lastName30') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName31', 'lastName31', 16) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName31'AND last_name like 'lastName31') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName32', 'lastName32', 16) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName32'AND last_name like 'lastName32') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName33', 'lastName33', 7) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName33'AND last_name like 'lastName33') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName34', 'lastName34', 19) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName34'AND last_name like 'lastName34') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName35', 'lastName35', 19) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName35'AND last_name like 'lastName35') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName36', 'lastName36', 9) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName36'AND last_name like 'lastName36') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName37', 'lastName37', 1) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName37'AND last_name like 'lastName37') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName38', 'lastName38', 17) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName38'AND last_name like 'lastName38') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName39', 'lastName39', 3) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName39'AND last_name like 'lastName39') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName40', 'lastName40', 18) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName40'AND last_name like 'lastName40') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName41', 'lastName41', 6) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName41'AND last_name like 'lastName41') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName42', 'lastName42', 15) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName42'AND last_name like 'lastName42') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName43', 'lastName43', 13) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName43'AND last_name like 'lastName43') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName44', 'lastName44', 11) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName44'AND last_name like 'lastName44') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName45', 'lastName45', 6) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName45'AND last_name like 'lastName45') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName46', 'lastName46', 18) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName46'AND last_name like 'lastName46') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName47', 'lastName47', 14) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName47'AND last_name like 'lastName47') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName48', 'lastName48', 4) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName48'AND last_name like 'lastName48') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName49', 'lastName49', 3) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName49'AND last_name like 'lastName49') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName50', 'lastName50', 1) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName50'AND last_name like 'lastName50') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName51', 'lastName51', 4) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName51'AND last_name like 'lastName51') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName52', 'lastName52', 11) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName52'AND last_name like 'lastName52') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName53', 'lastName53', 18) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName53'AND last_name like 'lastName53') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName54', 'lastName54', 10) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName54'AND last_name like 'lastName54') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName55', 'lastName55', 1) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName55'AND last_name like 'lastName55') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName56', 'lastName56', 5) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName56'AND last_name like 'lastName56') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName57', 'lastName57', 17) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName57'AND last_name like 'lastName57') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName58', 'lastName58', 17) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName58'AND last_name like 'lastName58') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName59', 'lastName59', 6) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName59'AND last_name like 'lastName59') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName60', 'lastName60', 7) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName60'AND last_name like 'lastName60') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName61', 'lastName61', 6) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName61'AND last_name like 'lastName61') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName62', 'lastName62', 16) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName62'AND last_name like 'lastName62') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName63', 'lastName63', 7) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName63'AND last_name like 'lastName63') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName64', 'lastName64', 3) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName64'AND last_name like 'lastName64') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName65', 'lastName65', 16) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName65'AND last_name like 'lastName65') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName66', 'lastName66', 8) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName66'AND last_name like 'lastName66') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName67', 'lastName67', 5) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName67'AND last_name like 'lastName67') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName68', 'lastName68', 6) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName68'AND last_name like 'lastName68') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName69', 'lastName69', 17) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName69'AND last_name like 'lastName69') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName70', 'lastName70', 1) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName70'AND last_name like 'lastName70') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName71', 'lastName71', 2) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName71'AND last_name like 'lastName71') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName72', 'lastName72', 9) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName72'AND last_name like 'lastName72') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName73', 'lastName73', 4) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName73'AND last_name like 'lastName73') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName74', 'lastName74', 3) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName74'AND last_name like 'lastName74') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName75', 'lastName75', 1) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName75'AND last_name like 'lastName75') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName76', 'lastName76', 12) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName76'AND last_name like 'lastName76') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName77', 'lastName77', 5) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName77'AND last_name like 'lastName77') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName78', 'lastName78', 19) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName78'AND last_name like 'lastName78') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName79', 'lastName79', 15) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName79'AND last_name like 'lastName79') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName80', 'lastName80', 4) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName80'AND last_name like 'lastName80') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName81', 'lastName81', 5) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName81'AND last_name like 'lastName81') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName82', 'lastName82', 8) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName82'AND last_name like 'lastName82') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName83', 'lastName83', 12) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName83'AND last_name like 'lastName83') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName84', 'lastName84', 7) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName84'AND last_name like 'lastName84') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName85', 'lastName85', 7) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName85'AND last_name like 'lastName85') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName86', 'lastName86', 14) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName86'AND last_name like 'lastName86') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName87', 'lastName87', 4) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName87'AND last_name like 'lastName87') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName88', 'lastName88', 18) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName88'AND last_name like 'lastName88') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName89', 'lastName89', 13) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName89'AND last_name like 'lastName89') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName90', 'lastName90', 16) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName90'AND last_name like 'lastName90') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName91', 'lastName91', 17) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName91'AND last_name like 'lastName91') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName92', 'lastName92', 12) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName92'AND last_name like 'lastName92') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName93', 'lastName93', 6) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName93'AND last_name like 'lastName93') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName94', 'lastName94', 14) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName94'AND last_name like 'lastName94') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName95', 'lastName95', 13) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName95'AND last_name like 'lastName95') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName96', 'lastName96', 13) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName96'AND last_name like 'lastName96') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName97', 'lastName97', 8) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName97'AND last_name like 'lastName97') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName98', 'lastName98', 6) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName98'AND last_name like 'lastName98') LIMIT 1;
INSERT INTO vote.player (first_name, last_name, position_id) SELECT * FROM (SELECT 'firstName99', 'lastName99', 7) AS tmp WHERE NOT EXISTS (SELECT first_name FROM vote.player WHERE first_name like 'firstName99'AND last_name like 'lastName99') LIMIT 1;

SET foreign_key_checks = 1;


